### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by Brightlcz** [zhaoyuzhi/D2HNet#2]
Hello, congratulations on your hard work being accepted by ECCV2022. I installed the environment according to README.
why do I get this error when training?

(d2hnet) amax@ict4-pc://mnt/D2HNet$ conda list |grep cuda
cudatoolkit               9.0                  h13b8566_0    defaults
pytorch                   1.1.0           py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
(d2hnet) amax@ict4-pc://mnt/D2HNet$ python train.py
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from trainer import Trainer, TwoPhaseTrainer
  File "/mnt/D2HNet/trainer.py", line 12, in <module>
    from models.loss import ColorLoss, VGGLoss
  File "/mnt/D2HNet/models/loss.py", line 9, in <module>
    from .utils import create_generator_val
  File "/mnt/D2HNet/models/utils.py", line 3, in <module>
    from models import network
  File "/mnt/D2HNet/models/network.py", line 5, in <module>
    from models import dcn_module
  File "/mnt/D2HNet/models/dcn_module.py", line 7, in <module>
    from dcn.deform_conv import ModulatedDeformConvPack2 as DCN
  File "/mnt/D2HNet/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack,
  File "/mnt/D2HNet/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: /mnt/D2HNet/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
(d2hnet) amax@ict4-pc://mnt/D2HNet$

**Comment by zhaoyuzhi** [comment]
It seems that you do not install DCN module. Please try this first:
```
cd dcn
python setup.py develop
```

**Comment by Brightlcz** [comment]
Thank you for your reply. @zhaoyuzhi 
This time, I downloaded the file again, and after installing the environment, I can test the pictures of xiaomi10 without installing the dcn model.
By the way， in the paper abstract, you said that D2HNet is developed to recover a high-quality image by deblurring and
enhancing a long-exposure image under the guidance of a short-exposure, but in the pipeline chart and code below, how do I feel that the short-exposure noise image is restored under the guidance of a long-exposure?
Thanks again.

**Comment by zhaoyuzhi** [comment]
Hi Brightlcz,

It is because the ground truth image in the training aligns with the short-exposure input image $s_{first}$. So, you may say that the noise removal is under the guidance of a long-exposure image since it is less noisy. But the main challenge of long-short-fusion is to align the long-exposure input image with the short-exposure input image; then, we can well use the textures from the long-exposure image. Based on this, we say it in the abstract (deblurring for the long-exposure image is under the guidance of the short-exposure image).

For instance, if the ground truth is $l_{last}$ (see ablation study 3)), you may not say the short-exposure noise image $s$ is restored under the guidance of the long-exposure image $l$.

**Comment by Brightlcz** [comment]
Hello, @zhaoyuzhi  thanks for your answer,
This appears to be an inconsistency in the claims due to differences in the selection of real photos. This question is so confusing.
